branches:
  except: /^v\d/
language: node_js
node_js: node
script: npm run-script pretest && npm run-script coverage
jobs:
  include:
  - dist: xenial
    after_success: npx istanbul-coveralls
  - os: windows
    script: node test.js
